name: Tests
on:
  push:
    tags:
      - test4.1.*

jobs:
  prebuild-node:
    name: 'Test on Node v${{ matrix.node }} ${{ matrix.os.name }}-${{ matrix.os.version }} ${{ matrix.arch }}'
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}

    strategy:
      matrix:
        os:
          - name: Ubuntu
            version: 20.04
          - name: macOS
            version: latest
          - name: Windows
            version: 2019
        node: ['12','13','14','15','16','17','18','19','20','21', '22']
        arch: [x64]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
      - name: Run tests
        env:
          OPENCV4NODEJS_DISABLE_AUTOBUILD: 1
        run: |
          echo installing
          npm ci --unsafe-perm
          npm run install
          echo running tests
          cd ./test
          npm ci --unsafe-perm
          npm test
          npm run test-externalMemTracking